### ISSUE TITLE
worker-edit and shift-time command doesn't handle extra parameters properly.

### ISSUE THREAD

**Issue by mkeoliya** [mkeoliya/ped#4]
No details provided.
![Screenshot 2020-10-30 at 12.19.54 PM.png](https://raw.githubusercontent.com/mkeoliya/ped/main/files/16a80367-1b66-4a99-a453-db625e29ba81.png)

If an extra parameter `j/0` is entered, the resulting message is incorrect.

**Comment by plosslaw** [comment]
The parameter prefix `j/` has never been specified in the User Guide so why should it be treated as a parameter prefix?

Hence when you use the parameter prefix `p/` , everything after the prefix up until another valid parameter prefix will be considered as the parameter for pay, in other words you are passing in the string `"1 j/0"` as a parameter for the worker's hourly pay and we output the correct error message as the hourly pay should be a number with a maximum of 2 decimal places.

We have no obligations to check for invalid parameter prefixes and treat strings containing `'/'` as parameter prefixes since such parameter prefixes have not been given in the User Guide.

**Comment by mkeoliya** [comment]
Yep, that's 100% my bad - must've mixed up `j/` with some other parameter - probably a result of skimming through a very comprehensive UG in under 20 minutes!  

Thanks for pointing this out, and sorry for the incorrect bug report! (from first-hand experience, its always unpleasant to address buggy bug reports).
